// GENERATED by design-system/scripts/build-tokens.py from tokens.json. Do not edit by hand.
// HELIX / Cyper Studio design tokens v0.1.1 (DRAFT until LOCK v1.0).

export const tokens = {
  color: {
    "bg": "#FFFFFF",
    "surface": "#F9FAFB",
    "border": "#E4E7EC",
    "border-strong": "#8691A3",
    "ink": "#0B1220",
    "text": "#475467",
    "muted": "#667085",
    "accent": "#1F4FE0",
    "accent-hover": "#1A42BD",
    "accent-pressed": "#15399F",
    "accent-tint": "#EEF3FF",
    "on-accent": "#FFFFFF",
    "success": "#067647",
    "success-tint": "#ECFDF3",
    "warning": "#B54708",
    "warning-tint": "#FFFAEB",
    "danger": "#B42318",
    "danger-tint": "#FEF3F2",
  },
  font: {
    "sans": "\"Geist\", system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
    "mono": "\"Geist Mono\", ui-monospace, \"SF Mono\", Menlo, Consolas, monospace",
  },
  type: {
    "display": { size: "clamp(2.5rem, 1rem + 5vw, 4.25rem)", lineHeight: "1.05", weight: "600", letterSpacing: "-0.03em" },
    "h1": { size: "clamp(2rem, 1rem + 3.4vw, 3.25rem)", lineHeight: "1.08", weight: "600", letterSpacing: "-0.025em" },
    "h2": { size: "clamp(1.75rem, 1rem + 2.5vw, 2.75rem)", lineHeight: "1.12", weight: "600", letterSpacing: "-0.02em" },
    "h3": { size: "1.25rem", lineHeight: "1.3", weight: "600", letterSpacing: "0" },
    "h4": { size: "1.125rem", lineHeight: "1.35", weight: "600", letterSpacing: "0" },
    "h5": { size: "1rem", lineHeight: "1.4", weight: "600", letterSpacing: "0" },
    "h6": { size: "0.875rem", lineHeight: "1.4", weight: "600", letterSpacing: "0.01em" },
    "body-lg": { size: "1.1875rem", lineHeight: "1.6", weight: "400", letterSpacing: "0" },
    "body": { size: "1.0625rem", lineHeight: "1.65", weight: "400", letterSpacing: "0" },
    "small": { size: "0.875rem", lineHeight: "1.5", weight: "400", letterSpacing: "0" },
    "caption": { size: "0.875rem", lineHeight: "1.45", weight: "400", letterSpacing: "0" },
    "label": { size: "0.8125rem", lineHeight: "1.4", weight: "500", letterSpacing: "0.06em" },
    "data": { size: "0.9375rem", lineHeight: "1.5", weight: "500", letterSpacing: "0" },
  },
  space: {
    "s1": "4px",
    "s2": "8px",
    "s3": "12px",
    "s4": "16px",
    "s5": "24px",
    "s6": "32px",
    "s7": "48px",
    "s8": "64px",
    "s9": "96px",
    "s10": "128px",
  },
  radius: {
    "sm": "6px",
    "md": "10px",
    "lg": "16px",
  },
  shadow: {
    "1": "0 1px 2px rgba(16, 24, 40, 0.06)",
    "2": "0 8px 24px -8px rgba(16, 24, 40, 0.12)",
  },
  motion: {
    "ease": "cubic-bezier(0.2, 0.7, 0.2, 1)",
    "t-fast": "150ms",
    "t-base": "250ms",
    "t-sheen": "600ms",
    "settle-y": "8px",
    "sheen": "rgb(255 255 255 / 0.18)",
  },
  layout: {
    "container": "1200px",
    "header-h": "64px",
    "btn-h": "44px",
    "btn-h-lg": "52px",
    "field-h": "44px",
    "measure": "65ch",
    "ring-w": "2px",
    "ring-offset": "2px",
    "hatch-line": "rgba(11, 18, 32, 0.045)",
    "hatch-step": "10px",
    "hairline": "1px",
    "icon": "20px",
    "marker": "24px",
    "bracket": "12px",
    "bracket-w": "1.5px",
    "textarea-min": "120px",
    "menu-link-h": "48px",
    "table-min": "40rem",
  },
  breakpoints: {
    "sm": "390px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px",
  },
} as const;

export type ColorToken = keyof typeof tokens.color;
export type SpaceToken = keyof typeof tokens.space;
export type TypeToken = keyof typeof tokens.type;

/** Returns the CSS custom property reference for a colour token, for example cssVar("accent") -> "var(--accent)". */
export const cssVar = (name: string): string => `var(--${name})`;
