// Accessibility and robustness checks per candidate. usage: node a11y.mjs <id> <url> [--out=...]
import { chromium } from '../../tools/node_modules/playwright-core/index.mjs';
import fs from 'node:fs';
const [id, url] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const res = { id, url };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const open = async (opts = {}, js = true) => { const ctx = await b.newContext({ viewport: { width: 1280, height: 720 }, javaScriptEnabled: js, ...opts }); const p = await ctx.newPage(); await p.goto(url, { waitUntil: 'load' }); await sleep(2000); return { ctx, p }; };
// 1 keyboard scrolling
{ const { ctx, p } = await open(); const sy = () => p.evaluate(() => Math.round(scrollY)); const out = {}; const max = await p.evaluate(() => document.documentElement.scrollHeight - innerHeight);
  await p.evaluate(() => document.activeElement && document.activeElement.blur());
  for (const [k, key] of [['Space', 'Space'], ['PageDown', 'PageDown'], ['ArrowDown x3', 'ArrowDown'], ['End', 'End'], ['Home', 'Home']]) { const before = await sy(); const n = k.includes('x3') ? 3 : 1; for (let i = 0; i < n; i++) await p.keyboard.press(key); await sleep(1800); out[k] = { before, after: await sy() }; }
  out.expect = { maxScroll: max, endReachedMax: out.End.after >= max - 2, homeReachedZero: out.Home.after === 0, spaceMoved: out.Space.after > out.Space.before, pageDownMoved: out.PageDown.after > out.PageDown.before };
  res.keyboardScroll = out; await ctx.close(); }
// 2 in-page anchors with sticky header (target must not sit under the 64px header)
{ const { ctx, p } = await open(); const out = {};
  for (const h of ['lit', 'steps', 'panels', 'end']) { await p.evaluate(() => scrollTo(0, 0)); await sleep(1200); await p.click(`.hdr nav a[href="#${h}"], .hdr .btn[href="#${h}"]`); await sleep(2200);
    out[h] = await p.evaluate(h => { const e = document.getElementById(h); const hd = document.querySelector('.hdr').getBoundingClientRect(); const r = (h === 'steps' || h === 'panels' ? e.querySelector('h2') : e).getBoundingClientRect(); return { targetTop: Math.round(r.top), headerBottom: Math.round(hd.bottom), hiddenUnderHeader: r.top < hd.bottom - 1 && r.bottom > 0 && (h === 'lit' || h === 'end'), scrollY: Math.round(scrollY) }; }, h); }
  res.anchors = out; await ctx.close(); }
// 3 find-in-page: window.find then is the match actually visible to a reader?
{ const { ctx, p } = await open(); const out = {};
  for (const term of ['Your name', 'Open for business', 'Set your brand', 'Panel 4 of 5']) { await p.evaluate(() => { scrollTo(0, 0); getSelection().removeAllRanges(); }); await sleep(900);
    out[term] = await p.evaluate(async t => { const found = window.find(t, false, false, true); await new Promise(r => setTimeout(r, 1500)); if (!found) return { found }; const sel = getSelection(); const rg = sel.getRangeAt(0); const rc = rg.getBoundingClientRect(); let el = rg.startContainer.nodeType === 3 ? rg.startContainer.parentElement : rg.startContainer; let op = 1; for (let e = el; e; e = e.parentElement) op *= parseFloat(getComputedStyle(e).opacity); return { found, inViewport: rc.left >= 0 && rc.right <= innerWidth && rc.top >= 60 && rc.bottom <= innerHeight, rect: [Math.round(rc.left), Math.round(rc.top), Math.round(rc.right), Math.round(rc.bottom)], effectiveOpacity: +op.toFixed(2), visuallyReadable: op > 0.5 && rc.left >= 0 && rc.right <= innerWidth && rc.top >= 60 && rc.bottom <= innerHeight }; }, term); }
  res.findInPage = out; await ctx.close(); }
// 4 200% zoom (640 x 360 css px at dpr 2)
{ const { ctx, p } = await open({ viewport: { width: 640, height: 360 }, deviceScaleFactor: 2 }); const out = await p.evaluate(() => { const q = s => document.querySelector(s); const ov = e => e && (e.scrollHeight > e.clientHeight + 2 || e.scrollWidth > e.clientWidth + 2); const clipped = [...document.querySelectorAll('h1,h2,h3,p,a,button')].filter(e => { const r = e.getBoundingClientRect(); return r.width > 0 && (r.right > innerWidth + 1) && !e.closest('.track'); }).length;
  return { docOverflowX: document.documentElement.scrollWidth - innerWidth, stepsStickOverflowsY: q('.steps__stick') ? q('.steps__stick').scrollHeight - q('.steps__stick').clientHeight : null, stepsStickH: q('.steps__stick') && Math.round(q('.steps__stick').getBoundingClientRect().height), elementsClippedRight: clipped }; });
  // read pinned step text at each progress point: is every step's text inside the sticky box at 200%?
  out.stepBoxes = await p.evaluate(async () => { const st = document.getElementById('steps'); const top = st.getBoundingClientRect().top + scrollY; const H = st.getBoundingClientRect().height - innerHeight; const rs = []; for (const f of [.1, .5, .9]) { scrollTo(0, top + f * H); await new Promise(r => setTimeout(r, 700)); const box = document.querySelector('.steps__stick').getBoundingClientRect(); const vis = [...document.querySelectorAll('.step')].filter(s => +getComputedStyle(s).opacity > .5)[0]; const r = vis && vis.getBoundingClientRect(); rs.push({ f, visibleStep: vis ? vis.querySelector('h3').textContent : null, fitsInBox: !!r && r.top >= box.top - 1 && r.bottom <= box.bottom + 1 }); } return rs; });
  res.zoom200 = out; await ctx.close(); }
// 5 reduced motion: nothing pinned, nothing hidden, no running animations, no overlap
{ const { ctx, p } = await open({ reducedMotion: 'reduce' }); const out = await p.evaluate(() => { const an = document.getAnimations().filter(a => a.playState === 'running').length; const op = [...document.querySelectorAll('.w,.step,.frame,h1 .line')].map(e => { let o = 1; for (let x = e; x; x = x.parentElement) o *= parseFloat(getComputedStyle(x).opacity); return o; }); const steps = [...document.querySelectorAll('.step')].map(s => s.getBoundingClientRect()); const overlap = steps.some((a, i) => steps.some((c, j) => j > i && a.bottom > c.top + 2 && a.top < c.bottom - 2)); const panels = [...document.querySelectorAll('.p')].map(e => e.getBoundingClientRect()); const track = getComputedStyle(document.querySelector('.track')).transform;
  return { runningAnimations: an, minOpacityOfMotionElements: +Math.min(...op).toFixed(2), stepsOverlap: overlap, trackTransform: track, panelsAllWithinViewportWidth: panels.every(r => r.left >= 0 && r.right <= innerWidth + 1), pageHeight: document.documentElement.scrollHeight, pinnedHeights: [document.getElementById('steps').offsetHeight, document.getElementById('panels').offsetHeight], lenisActive: !!window.__lenis, gsapPins: document.querySelectorAll('.pin-spacer').length }; }); res.reducedMotion = out; await ctx.close(); }
// 6 JS off: content visible and readable (timers do not run with JS disabled, so waiting happens in Node)
{ const { ctx, p } = await open({}, false);
  await p.evaluate(() => { const lit = document.querySelector('[data-lit]'); scrollBy(0, lit.getBoundingClientRect().bottom - 0.3 * innerHeight); }); await sleep(900);
  const out = await p.evaluate(() => { const op = e => { let o = 1; for (let x = e; x; x = x.parentElement) o *= parseFloat(getComputedStyle(x).opacity); return o; }; const ws = [...document.querySelectorAll('.w')].map(op); const steps = [...document.querySelectorAll('.step')].map(s => s.getBoundingClientRect()); return { h1: document.querySelector('h1').innerText.replace(/\s+/g, ' ').trim(), litWordsMinOpacityAtParagraphEnd: ws.length ? +Math.min(...ws).toFixed(2) : 'n/a (paragraph is plain text)', litChars: document.querySelector('[data-lit]').innerText.length, frameOpacity: +op(document.querySelector('.frame')).toFixed(2), stepsOverlap: steps.some((a, i) => steps.some((c, j) => j > i && a.bottom > c.top + 2 && a.top < c.bottom - 2)), pageHeight: document.documentElement.scrollHeight, cssAnimationsRunning: document.getAnimations().length }; }); res.jsOff = out; await ctx.close(); }
// 7 touch: native touch scroll distance for the same gesture
{ const { ctx, p } = await open({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true }); const cdp = await ctx.newCDPSession(p); const y0 = await p.evaluate(() => scrollY);
  const dists = []; for (let i = 0; i < 3; i++) { const a = await p.evaluate(() => scrollY); await cdp.send('Input.synthesizeScrollGesture', { x: 195, y: 600, yDistance: -600, speed: 1800, gestureSourceType: 'touch' }); await sleep(1500); dists.push(Math.round((await p.evaluate(() => scrollY)) - a)); }
  res.touch = { gestureDistance: 600, resultingDeltas: dists, lenisSyncTouch: await p.evaluate(() => window.__lenis ? window.__lenis.options.syncTouch : 'no lenis'), scrollBehavior: await p.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior) }; await ctx.close(); }
// 8 reading order (aria snapshot text sequence)
{ const { ctx, p } = await open(); const snap = await p.locator('body').ariaSnapshot(); res.readingOrder = snap.split('\n').map(l => l.replace(/^\s*-\s*/, '').replace(/\[.*?\]/g, '').trim()).filter(Boolean); res.readingOrderLines = res.readingOrder.length; await ctx.close(); }
await b.close();
fs.writeFileSync(`../results/a11y-${id}.json`, JSON.stringify(res, null, 1));
const k = res.keyboardScroll.expect, a = res.anchors;
console.log(id.padEnd(8), 'kbd', JSON.stringify(k), '| anchors under header:', Object.entries(a).filter(([, v]) => v.hiddenUnderHeader).map(([h]) => h).join(',') || 'none', '| find readable:', Object.entries(res.findInPage).map(([t, v]) => `${t}=${v.visuallyReadable}`).join('; '), '| RM overlap', res.reducedMotion.stepsOverlap, 'anim', res.reducedMotion.runningAnimations, '| noJS litMinOp', res.jsOff.litWordsMinOpacityAtParagraphEnd, '| touch', res.touch.resultingDeltas.join(','));
