// Non-timing checks for the four heroes: four-question test, server HTML, JS off, no HELIX blue in tenant windows (all tenant states), axe, focus order, reduced motion.
import { chromium } from '../../tools/node_modules/playwright-core/index.mjs';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const axeSrc = fs.readFileSync('../../tools/node_modules/axe-core/axe.min.js', 'utf8');
const BASE = 'http://127.0.0.1:4174/home-lab/heroes/';
const HEROES = { A: 'hero-a-reskin.html', B: 'hero-b-editorial.html', C: 'hero-c-pair.html', D: 'hero-d-your-name.html' };
const BLUE = [65, 97, 244];
const lin = c => { c /= 255; return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; };
const lab = ([r, g, b]) => { r = lin(r); g = lin(g); b = lin(b); const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b), m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b), s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b); return [0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s, 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s, 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s]; };
const dE = (a, b) => { const A = lab(a), B = lab(b); return Math.hypot(A[0] - B[0], A[1] - B[1], A[2] - B[2]); };
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const out = {};
const PAINTED = () => { const vh = innerHeight; const res = []; const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let t; while ((t = w.nextNode())) { const s = t.textContent.replace(/\s+/g, ' ').trim(); if (!s) continue; let o = 1, ok = true; for (let e = t.parentElement; e; e = e.parentElement) { const c = getComputedStyle(e); o *= parseFloat(c.opacity); if (c.display === 'none' || c.visibility === 'hidden' || e.hasAttribute('aria-hidden') && 0) ok = false; } const r = document.createRange(); r.selectNodeContents(t); const bb = r.getBoundingClientRect(); if (ok && o > 0.05 && bb.width > 0 && bb.top < vh && bb.bottom > 0 && bb.left < innerWidth) res.push(s); } return res.join(' | '); };
for (const [id, f] of Object.entries(HEROES)) {
  const o = out[id] = { file: f };
  // server HTML
  const html = await (await fetch(BASE + f)).text();
  o.bytes = { html: Buffer.byteLength(html), cssInline: (html.match(/<style>([\s\S]*?)<\/style>/) || ['', ''])[1].length, jsInline: [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].reduce((s, m) => s + m[1].length, 0) };
  const body = html.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<style[\s\S]*?<\/style>/g, '');
  o.serverHtml = { h1: /<h1[\s>]/.test(html), sub: /multi-tenant logistics operating system/.test(html), primaryCta: /btn btn--lg[^>]*>Request a demo/.test(html), trustLine: /Trusted by 10\+ logistics companies/.test(html), entityLine: /Built by Cyper Studio, a product engineering company in India\. Founded in 2024\./.test(html), email: html.includes('info@cyper.studio'), canonical: html.includes('<link rel="canonical" href="https://cyper.studio/">'), ogUrl: html.includes('<meta property="og:url" content="https://cyper.studio/">'), jsonLdFoundingDate2024: /"foundingDate":"2024"/.test(html), jsonLdOrg: /"@type":"Organization"/.test(html) };
  // four-question test per viewport
  o.firstViewport = {};
  for (const [vn, vp, mobile] of [['1440x800', { width: 1440, height: 800 }, false], ['390x844', { width: 390, height: 844 }, true]]) {
    const ctx = await b.newContext({ viewport: vp, deviceScaleFactor: mobile ? 2 : 1, isMobile: mobile, hasTouch: mobile }); const p = await ctx.newPage(); await p.goto(BASE + f, { waitUntil: 'load' }); await sleep(900);
    const txt = await p.evaluate(PAINTED);
    const cta = await p.evaluate(() => { const vh = innerHeight; const els = [...document.querySelectorAll('.btn')].filter(e => { const r = e.getBoundingClientRect(); return r.top >= 0 && r.bottom <= vh && r.width > 0; }); return { primaryFilledInViewport: els.filter(e => !e.classList.contains('btn--quiet')).length, quietHeader: els.filter(e => e.classList.contains('btn--quiet')).length, primaryHeightPx: Math.round((els.find(e => e.classList.contains('btn--lg')) || { getBoundingClientRect: () => ({ height: 0 }) }).getBoundingClientRect().height) }; });
    const q = { company: /Cyper Studio/.test(txt) && /product engineering company in India/.test(txt), product: /HELIX/.test(txt) && /logistics operating system|logistics software|shipping platform/i.test(txt), audience: /couriers/i.test(txt) && /3PLs/i.test(txt) && /India/.test(txt), outcome: /branded shipping platform|own branded/i.test(txt), cta: cta.primaryFilledInViewport === 1, trustLine: /Trusted by 10\+/.test(txt), entityLine: /Founded in 2024/.test(txt) };
    o.firstViewport[vn] = { answers: q, allFourPass: q.company && q.product && q.audience && q.outcome, ctaInfo: cta, hScroll: await p.evaluate(() => document.documentElement.scrollWidth > innerWidth), productVisibleInViewport: await p.evaluate(() => { const vh = innerHeight; const e = document.querySelector('.tw,.con'); if (!e) return false; const r = e.getBoundingClientRect(); return r.top < vh - 40; }) };
    await ctx.close();
  }
  // JS off
  { const ctx = await b.newContext({ viewport: { width: 1440, height: 800 }, javaScriptEnabled: false }); const p = await ctx.newPage(); await p.goto(BASE + f, { waitUntil: 'load' }); await sleep(500); const txt = await p.evaluate(PAINTED); o.jsOff = { h1Visible: /Run your own|White-label logistics software/.test(txt), subVisible: /multi-tenant logistics operating system|branded shipping platform on HELIX/.test(txt), ctaVisible: /Request a demo/.test(txt), trustVisible: /Trusted by 10\+/.test(txt), entityVisible: /Founded in 2024/.test(txt), tenantControlsHidden: await p.evaluate(() => { const e = document.querySelector('.switch,.try'); return e ? getComputedStyle(e).display === 'none' : 'n/a'; }), horizontalScroll: await p.evaluate(() => document.documentElement.scrollWidth > innerWidth) }; await ctx.close(); }
  // reduced motion + axe + focus order + tenant-window colour audit (all states)
  { const ctx = await b.newContext({ viewport: { width: 1440, height: 800 }, reducedMotion: 'reduce' }); const p = await ctx.newPage(); await p.goto(BASE + f, { waitUntil: 'load' }); await sleep(4500);
    o.reducedMotion = { runningAnimations: await p.evaluate(() => document.getAnimations().filter(a => a.playState === 'running').length), tenantAutoAdvanced: id === 'A' ? await p.evaluate(() => document.querySelector('.switch [aria-pressed="true"]').textContent.trim()) : 'n/a' };
    await p.addScriptTag({ content: axeSrc }); const ax = await p.evaluate(async () => { const r = await axe.run(document, { runOnly: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa', 'best-practice'] }); return { violations: r.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.length, sample: v.nodes[0] && v.nodes[0].target.join(' ').slice(0, 80), msg: (v.nodes[0] && v.nodes[0].any[0] && v.nodes[0].any[0].message || '').slice(0, 140) })), passes: r.passes.length, incomplete: r.incomplete.map(v => v.id) }; }); o.axe = ax;
    // tenant window colours in every state
    const states = id === 'A' ? [0, 1, 2] : id === 'D' ? [0, 1, 2] : [0];
    const colourScan = () => [...document.querySelectorAll('.tw, .tw *')].flatMap(e => { const s = getComputedStyle(e); return [s.color, s.backgroundColor, s.borderTopColor, s.borderLeftColor, s.outlineColor, s.fill, s.boxShadow].filter(Boolean); });
    const found = new Set(); let minD = 9, closest = '';
    for (const st of states) { if (id === 'A') await p.click(`[data-i="${st}"]`); if (id === 'D') await p.click(`.dots [data-i="${st}"]`); await sleep(400); const cs = await p.evaluate(colourScan); for (const c of cs) for (const m of c.matchAll(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/g)) { const a = m[4] === undefined ? 1 : +m[4]; if (a < 0.05) continue; const rgb = [+m[1], +m[2], +m[3]]; const k = rgb.join(','); if (found.has(k)) continue; found.add(k); const d = dE(rgb, BLUE); if (d < minD) { minD = d; closest = `rgb(${k})`; } } }
    o.tenantWindow = { statesChecked: states.length, distinctColours: found.size, minDistanceToHelixBlue_OKLab: +minD.toFixed(3), closestColour: closest, helixBluePresent: [...found].includes(BLUE.join(',')), pass: minD > 0.1 };
    await ctx.close(); }
  // focus order (fresh page, no prior clicks)
  { const ctx = await b.newContext({ viewport: { width: 1440, height: 800 } }); const p = await ctx.newPage(); await p.goto(BASE + f, { waitUntil: 'load' }); await sleep(500); const order = []; for (let i = 0; i < 14; i++) { await p.keyboard.press('Tab'); order.push(await p.evaluate(() => { const e = document.activeElement; if (!e || e === document.body) return 'body'; const cs = getComputedStyle(e); return `${e.tagName.toLowerCase()}:${(e.getAttribute('aria-label') || e.innerText || e.id || '').replace(/\s+/g, ' ').trim().slice(0, 28)}|outline ${cs.outlineWidth}`; })); } o.focusOrder = order; await ctx.close(); }
  // form
  { const ctx = await b.newContext({ viewport: { width: 1440, height: 800 } }); const p = await ctx.newPage(); await p.goto(BASE + f, { waitUntil: 'load' }); o.form = await p.evaluate(() => ({ requiredFields: document.querySelectorAll('.form [required]').length, optionalFields: [...document.querySelectorAll('.form input:not([required]):not(.hp), .form textarea:not([required]), .form select:not([required])')].length, honeypot: !!document.querySelector('.hp'), successState: !!document.querySelector('.form__ok'), responseExpectationPlaceholder: /\{\{CONFIRM: reply within X business days\}\}/.test(document.querySelector('.form__ok').textContent) })); 
    // submit empty -> invalid; fill -> success
    await p.fill('#f-name', 'Test'); await p.fill('#f-mail', 'x'); await p.click('.form button[type=submit]'); o.form.invalidEmailBlocks = await p.evaluate(() => !document.querySelector('.form').classList.contains('sent')); await p.fill('#f-mail', 'a@b.co'); await p.fill('#f-co', 'Acme'); await p.selectOption('#f-type', '3PL'); await p.click('.form button[type=submit]'); o.form.successShown = await p.evaluate(() => document.querySelector('.form').classList.contains('sent') && getComputedStyle(document.querySelector('.form__ok')).display !== 'none'); await ctx.close(); }
}
await b.close();
fs.writeFileSync('../results/measure.json', JSON.stringify(out, null, 1));
for (const [id, o] of Object.entries(out)) console.log(id, 'bytes', o.bytes.html, '| 4Q 1440', o.firstViewport['1440x800'].allFourPass, '390', o.firstViewport['390x844'].allFourPass, '| CTA@1440', o.firstViewport['1440x800'].ctaInfo.primaryFilledInViewport, '@390', o.firstViewport['390x844'].ctaInfo.primaryFilledInViewport, '| trust@390', o.firstViewport['390x844'].answers.trustLine, '| jsOff', JSON.stringify(Object.values(o.jsOff)), '| window dE', o.tenantWindow.minDistanceToHelixBlue_OKLab, '| axe', o.axe.violations.map(v => v.id + '×' + v.nodes).join(',') || 'none', '| form', o.form.requiredFields, '+', o.form.optionalFields);
