// Builds markdown tables for HERO_REPORT.md / TRUST_CHECKLIST_RESULTS.md from heroes/results/measure.json and the Lighthouse JSON.
import fs from 'node:fs';
const m = JSON.parse(fs.readFileSync('../results/measure.json', 'utf8'));
const LH = id => { try { return JSON.parse(fs.readFileSync(`../../motion-bench/results/lh-${id}.json`, 'utf8')); } catch { return null; } };
const kb = b => (b / 1024).toFixed(1);
const out = [];
const T = (title, head, rows) => out.push(`### ${title}\n\n| ${head.join(' | ')} |\n|${head.map(() => '---').join('|')}|\n${rows.map(r => '| ' + r.join(' | ') + ' |').join('\n')}\n`);
const ids = [['A', 'hero-a', 'HERO-A'], ['B', 'hero-b', 'HERO-B'], ['C', 'hero-c', 'HERO-C'], ['D', 'hero-d', 'HERO-D'], [null, 'baseline', 'Baseline (Reference-page.html)']];
T('Weight and mobile Lighthouse (5 runs, medians)', ['Hero', 'HTML bytes (inline CSS + JS)', 'LCP', 'CLS', 'TBT', 'perf scores (5 runs)', 'a11y / best-practices / SEO (run 1)', 'requests'],
  ids.map(([k, id, name]) => { const l = LH(id); const mm = k && m[k]; return [name, mm ? `${kb(mm.bytes.html)} KB (${kb(mm.bytes.cssInline)} KB CSS, ${kb(mm.bytes.jsInline)} KB JS)` : 'n/a (external fonts)', l ? (l.median.lcp / 1000).toFixed(2) + ' s' : 'NOT RUN', l ? l.median.cls : '', l ? Math.round(l.median.tbt) + ' ms' : '', l ? l.runs.map(r => r.perf).join(', ') : '', l ? `${l.runs[0].a11y} / ${l.runs[0].bp} / ${l.runs[0].seo}` : '', l ? l.runs[0].requests : '']; }));
T('First viewport: the four questions as read from the rendered text (script)', ['Hero', '1440 x 800: company / product / audience / outcome', '390 x 844: same', 'filled CTAs in view (1440 / 390)', 'trust-line placeholder in view (1440 / 390)', 'product frame in view (1440 / 390)', 'horizontal scroll (1440 / 390)'],
  Object.entries(m).map(([k, o]) => { const a = o.firstViewport['1440x800'], b = o.firstViewport['390x844']; const f = x => ['company', 'product', 'audience', 'outcome'].map(q => x.answers[q] ? 'Y' : 'N').join(' '); return ['HERO-' + k, f(a), f(b), `${a.ctaInfo.primaryFilledInViewport} / ${b.ctaInfo.primaryFilledInViewport}`, `${a.answers.trustLine ? 'Y' : 'N'} / ${b.answers.trustLine ? 'Y' : 'N'}`, `${a.productVisibleInViewport ? 'Y' : 'N'} / ${b.productVisibleInViewport ? 'Y' : 'N'}`, `${a.hScroll ? 'YES' : 'no'} / ${b.hScroll ? 'YES' : 'no'}`]; }));
T('Server HTML and JS off', ['Hero', 'h1, sub, filled CTA, trust line, entity line, info@ in the HTML response', 'canonical, og:url, JSON-LD (Organization, founding 2024)', 'with JS disabled: h1 / sub / CTA / trust / entity painted', 'tenant-only controls hidden without JS', 'reduced motion: running animations'],
  Object.entries(m).map(([k, o]) => { const s = o.serverHtml, j = o.jsOff; return ['HERO-' + k, [s.h1, s.sub, s.primaryCta, s.trustLine, s.entityLine, s.email].map(x => x ? 'Y' : 'N').join(' '), [s.canonical, s.ogUrl, s.jsonLdOrg && s.jsonLdFoundingDate2024].map(x => x ? 'Y' : 'N').join(' '), [j.h1Visible, j.subVisible, j.ctaVisible, j.trustVisible, j.entityVisible].map(x => x ? 'Y' : 'N').join(' '), String(j.tenantControlsHidden), String(o.reducedMotion.runningAnimations)]; }));
T('Accessibility, colour, form', ['Hero', 'axe violations (WCAG 2.2 A/AA + best practice, 1440)', 'HELIX blue in tenant window: distinct colours checked / nearest colour to #4161F4 (OKLab)', 'required + optional fields', 'invalid email blocks submit / success state shown', 'first 6 tab stops'],
  Object.entries(m).map(([k, o]) => ['HERO-' + k, o.axe.violations.length ? o.axe.violations.map(v => `${v.id} x${v.nodes}`).join(', ') : 'none', k === 'B' ? 'no tenant window (operator console only)' : `${o.tenantWindow.distinctColours} / ${o.tenantWindow.closestColour} at ${o.tenantWindow.minDistanceToHelixBlue_OKLab}`, `${o.form.requiredFields} + ${o.form.optionalFields}`, `${o.form.invalidEmailBlocks ? 'Y' : 'N'} / ${o.form.successShown ? 'Y' : 'N'}`, o.focusOrder.slice(0, 6).map(x => x.split('|')[0]).join(' > ')]));
fs.writeFileSync('../results/tables.md', out.join('\n')); console.log('ok');
