#!/usr/bin/env python3
"""Generate tokens.css, tokens.ts, contrast.md and the Lab manifest from tokens.json.

Usage (from the repository root):  python3 -I docs/design-system/build-tokens.py
Exit code 1 if any contrast pair fails its required ratio.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
T = json.load(open(os.path.join(HERE, 'tokens.json')))


def rgb(h):
    h = h.lstrip('#'); return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def lum(h):
    f = lambda c: (c/255)/12.92 if c/255 <= 0.03928 else (((c/255)+0.055)/1.055)**2.4
    r, g, b = rgb(h); return 0.2126*f(r)+0.7152*f(g)+0.0722*f(b)

def ratio(a, b):
    la, lb = lum(a), lum(b); hi, lo = max(la, lb), min(la, lb); return (hi+0.05)/(lo+0.05)

C = {k: v['value'] for k, v in T['color'].items()}

# ---------------------------------------------------------------- tokens.css
L = ['/* GENERATED by docs/design-system/build-tokens.py from tokens.json. Do not edit by hand.',
     f"   HELIX / Cyper Studio design tokens v{T['version']} (DRAFT until LOCK v1.0). Light mode only. */", '',
     ':root {', '  color-scheme: light;', '', '  /* Colour */']
for k, v in T['color'].items(): L.append(f"  --{k}: {v['value']};")
L += ['', '  /* Font */']
for k, v in T['font'].items(): L.append(f"  --font-{k}: {v['value']};")
L += ['', '  /* Type scale: --fs-*, --lh-*, --fw-*, --ls-* */']
for k, v in T['type'].items():
    if k.startswith('_'): continue
    L += [f"  --fs-{k}: {v['size']};", f"  --lh-{k}: {v['lh']};", f"  --fw-{k}: {v['weight']};", f"  --ls-{k}: {v['ls']};"]
L += ['', '  /* Space (4px base) */']
for k, v in T['space'].items(): L.append(f"  --{k}: {v};")
L += ['', '  /* Radius */']
for k, v in T['radius'].items(): L.append(f"  --r-{k}: {v['value']};")
L += ['', '  /* Elevation (product frames only) */']
for k, v in T['shadow'].items(): L.append(f"  --shadow-{k}: {v['value']};")
L += ['', '  /* Motion */']
for k, v in T['motion'].items(): L.append(f"  --{k}: {v['value']};")
L += ['', '  /* Layout and controls */']
for k, v in T['layout'].items(): L.append(f"  --{k}: {v['value']};")
L += ['', '  /* Responsive layout values (overridden at 768px below) */', '  --gutter: 20px;', '  --sec-pad: var(--s8);', '}', '',
      '@media (min-width: 768px) {', '  :root {', '    --gutter: 24px;', '    --sec-pad: var(--s9);', '  }', '}', '']
css = '\n'.join(L)

# ---------------------------------------------------------------- tokens.ts
def js(v): return json.dumps(v, ensure_ascii=False)
ts = ['// GENERATED by docs/design-system/build-tokens.py from tokens.json. Do not edit by hand.',
      f"// HELIX / Cyper Studio design tokens v{T['version']} (DRAFT until LOCK v1.0).", '',
      'export const tokens = {']
ts.append('  color: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['color'].items()]; ts.append('  },')
ts.append('  font: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['font'].items()]; ts.append('  },')
ts.append('  type: {')
for k, v in T['type'].items():
    if k.startswith('_'): continue
    ts.append(f"    {js(k)}: {{ size: {js(v['size'])}, lineHeight: {js(v['lh'])}, weight: {js(v['weight'])}, letterSpacing: {js(v['ls'])} }},")
ts.append('  },')
ts.append('  space: {'); ts += [f"    {js(k)}: {js(v)}," for k, v in T['space'].items()]; ts.append('  },')
ts.append('  radius: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['radius'].items()]; ts.append('  },')
ts.append('  shadow: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['shadow'].items()]; ts.append('  },')
ts.append('  motion: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['motion'].items()]; ts.append('  },')
ts.append('  layout: {'); ts += [f"    {js(k)}: {js(v['value'])}," for k, v in T['layout'].items()]; ts.append('  },')
ts.append('  breakpoints: {'); ts += [f"    {js(k)}: {js(v)}," for k, v in T['breakpoints'].items() if not k.startswith('_')]; ts.append('  },')
ts.append('} as const;')
ts += ['', 'export type ColorToken = keyof typeof tokens.color;', 'export type SpaceToken = keyof typeof tokens.space;', 'export type TypeToken = keyof typeof tokens.type;', '',
       '/** Returns the CSS custom property reference for a colour token, for example cssVar("accent") -> "var(--accent)". */',
       'export const cssVar = (name: string): string => `var(--${name})`;', '']
tsx = '\n'.join(ts)

# ---------------------------------------------------------------- contrast
rows = ['| Pair | Foreground | Background | Ratio | Required | Result |', '|---|---|---|---|---|---|']
fails = []
pairs_out = []
for p in T['pairs']:
    fg, bg = C[p['fg']], C[p['bg']]; r = ratio(fg, bg); mn = p['min']
    res = 'n/a (decorative)' if mn is None else ('PASS' if r >= mn else 'FAIL')
    if res == 'FAIL': fails.append(p['name'])
    rows.append(f"| {p['name']} | `{p['fg']}` {fg} | `{p['bg']}` {bg} | {r:.2f}:1 | {'>= '+str(mn)+':1' if mn else 'none'} | {res} |")
    pairs_out.append(dict(name=p['name'], fg=p['fg'], fgHex=fg, bg=p['bg'], bgHex=bg, ratio=round(r, 2), min=mn, result=res))
md = ['# Contrast table (script-computed)', '', f"Generated by `build-tokens.py` from `tokens.json` v{T['version']} using WCAG 2.x relative luminance. {len(T['pairs'])} pairs; **{len(fails)} failing**.",
      '', 'Text pairs need 4.5:1 (large text 3:1). UI component boundaries and focus indicators need 3:1 (WCAG 1.4.11). Decorative hairlines have no requirement and must never be the only way to identify a control.', ''] + rows + ['']
open(os.path.join(HERE, 'contrast.md'), 'w').write('\n'.join(md))
open(os.path.join(HERE, 'tokens.css'), 'w').write(css)
open(os.path.join(HERE, 'tokens.ts'), 'w').write(tsx)

# ---------------------------------------------------------------- Lab copies and manifest
lab_comp = os.path.join(ROOT, 'design-system', 'components'); os.makedirs(lab_comp, exist_ok=True)
open(os.path.join(lab_comp, 'tokens.css'), 'w').write(css)
names = ['--' + k for k in T['color']] + ['--font-' + k for k in T['font']]
for k, v in T['type'].items():
    if not k.startswith('_'): names += [f'--fs-{k}', f'--lh-{k}', f'--fw-{k}', f'--ls-{k}']
names += ['--' + k for k in T['space']] + ['--r-' + k for k in T['radius']] + ['--shadow-' + k for k in T['shadow']] + ['--' + k for k in T['motion']] + ['--' + k for k in T['layout']]
lab_dir = os.path.join(ROOT, 'design-system', 'lab'); os.makedirs(lab_dir, exist_ok=True)
open(os.path.join(lab_dir, 'tokens-manifest.js'), 'w').write('/* GENERATED: names of tokens the Lab can export. */\nwindow.HX_TOKEN_NAMES = ' + json.dumps(names) + ';\nwindow.HX_TOKEN_VERSION = ' + json.dumps(T['version']) + ';\n')
json.dump(pairs_out, open(os.path.join(HERE, 'contrast.json'), 'w'), indent=1)

print(f"tokens.css {len(css)}B, tokens.ts {len(tsx)}B, contrast pairs {len(T['pairs'])}, failing {len(fails)}")
if fails:
    print('FAIL:', '; '.join(fails)); sys.exit(1)
